# https://docs.github.com/en/free-pro-team@latest/actions
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request_target:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: system info
        run: |
          set -x
          id
          uname -a
          pwd
          env

      - name: Reject if more than one file is changed
        if: ${{ github.event.pull_request.changed_files != 1 }}
        run: |
          echo "ERROR: more than one file has been changed ..."
          exit 1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          set -x
          echo MARK-001
          git diff origin/main --
          git diff --name-only origin/main --
          git diff origin/main -- list.csv | sed  '/^index/,+2d' | sed -n 's/^+//gp'
