name: CI-Validate
on:
  pull_request_target:
    branches: [ main ]

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/validate-action
      - run: |
          cat - > event.json <<EOF
          ${{ toJson( github.event ) }}
          EOF
          npx -p "https://github.com/haheskja/scp-cli#master" dhis2-scp-cli -vvv pr-verify event.json
